### ISSUE TITLE
Add option to kill tmux session if not connected to within a certain time period

### ISSUE THREAD

**Issue by telotortium** [lhotari/action-upterm#17]
Use case: I've set up my [workflow](https://github.com/kidd/org-gcal.el/blob/master/.github/workflows/main.yml) to automatically run the upterm action if the job fails. This works really well, except for one thing - it causes the action not to complete for hours if there's a failure, because the upterm server just waits there. I could set [`timeout-minutes`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes) on the entire step, but that will kill the terminal even if a user connects to it. Instead, I'd like it if there were a `timeout-minutes` field specific to this action that terminates the action if no one SSH's to the server within that number of minutes, but keeps the terminal open if someone connects.

**Comment by bsgrigorov** [comment]
This would be amazing! When can we expect this to be available?

**Comment by telotortium** [comment]
@bsgrigorov waiting on approval of #18

**Comment by bsgrigorov** [comment]
@telotortium Shouldn't there be a timeout even if someone connects to the server? I've had instances where I connected to the server and forgot to terminate the session and github actions kept running for 3-4 hours. It would be great if we can set a session TTL. Default could be like 20 mins.

**Comment by lhotari** [comment]
> @telotortium Shouldn't there be a timeout even if someone connects to the server? I've had instances where I connected to the server and forgot to terminate the session and github actions kept running for 3-4 hours. It would be great if we can set a session TTL. Default could be like 20 mins.

@bsgrigorov I should be possible to implement that using bash's existing feature where the timeout is configured with the `TMOUT` environment variable. Would you want to give it a try?

**Comment by bsgrigorov** [comment]
I realized you can set timeout-minutes parameter on either the GitHub Actions step or job.
