### ISSUE TITLE
What's the difference with owenthereal/action-upterm?

### ISSUE THREAD

**Issue by adoyle-h** [lhotari/action-upterm#28]
https://github.com/owenthereal/action-upterm

**Comment by owenthereal** [comment]
I'm the author of [upterm](https://github.com/owenthereal/upterm) and currently maintain [owenthereal/action-upterm](https://github.com/owenthereal/action-upterm), which initially started as a fork of this repository. I aim to provide a more up-to-date experience by integrating `upterm` with GitHub Actions in my fork.

I want to thank @lhotari for initiating the integration of `upterm` with GitHub Actions, which has been a great source of inspiration for my work.

Thank you!
