### ISSUE TITLE
Support other Linux besides Debian

### ISSUE THREAD

**Issue by duartealexf** [lhotari/action-upterm#6]
Currently it does not seem to work with my non-Debian Linux. I believe my runner is a RHEL or CentOS, I can't be really sure, but either way I run into this error:

![image](https://user-images.githubusercontent.com/5911016/121232738-4b468980-c868-11eb-8948-0b0a2415e712.png)

Or am I doing something wrong?

This is the action step:
```yml
      - name: Debug
        uses: lhotari/action-upterm@v1
```

**Comment by lhotari** [comment]
Problem addressed by 0a4cf57e995047afc0ad514400ae76fcf63a43fd . The pre-condition is that `tmux` must be installed. I'll close this issue. Please re-open if the solution doesn't work for you.
